%let metaserver_host = "server.foo.ch";

proc iomoperate;
  connect host    = &metaserver_host
          port    =  8561
       /* user    = &user,
          pass    = &password

          Use Kerberos instead of username/password:  */
          iomopts = 'securitypackage=Negotiate,securitypackagelist=Kerberos';

  list commands; 
quit;
/*
CONNECT
CONTINUE CLUSTER
CONTINUE SERVER
DISCONNECT
FLUSH AUTHORIZATION CACHE
LIST ATTRIBUTES
LIST CATEGORIES
LIST CLASSIDS
LIST CLIENTS
LIST CLUSTER CLIENTS
LIST CLUSTER SESSIONS
LIST CLUSTER STATE
LIST COMMANDS
LIST DEFINED SERVERS
LIST DNSNAME
LIST INFORMATION
LIST LOG
LIST LOG CONFIGURATION
LIST SERVERTIME
LIST SESSIONS
LIST STATE
LIST TYPES
LIST UNIQUEID
PAUSE CLUSTER
PAUSE SERVER
QUIESCE CLUSTER
QUIESCE SERVER
RESET CLUSTER PERFORMANCE
RESET PERFORMANCE
SET ATTRIBUTE
SET LOG CONFIGURATION
STOP CLUSTER
STOP SERVER
STOP SESSION
*/
