proc options
     listgroups;
run;

proc options group=adabas           ; run;
proc options group=animation        ; run;
proc options group=codegen          ; run;
proc options group=communications   ; run;
proc options group=datacom          ; run;
proc options group=dataquality      ; run;
proc options group=db2              ; run;
proc options group=email            ; run;
proc options group=envdisplay       ; run;
proc options group=envfiles         ; run;
proc options group=errorhandling    ; run;
proc options group=execmodes        ; run;
proc options group=extfiles         ; run;
proc options group=graphics         ; run;
proc options group=help             ; run;
proc options group=idms             ; run;
proc options group=ims              ; run;
proc options group=inputcontrol     ; run;
proc options group=install          ; run;
proc options group=ispf             ; run;
proc options group=languagecontrol  ; run;
proc options group=listcontrol      ; run;
proc options group=logcontrol       ; run;
proc options group=log_listcontrol  ; run;
proc options group=macro            ; run;
proc options group=memory           ; run;
proc options group=meta             ; run;
proc options group=odsprint         ; run;
proc options group=pdf              ; run;
proc options group=performance      ; run;
proc options group=rexx             ; run;
proc options group=sasfiles         ; run;
proc options group=security         ; run;
proc options group=smf              ; run;
proc options group=sort             ; run;
proc options group=sql              ; run;
proc options group=svg              ; run;
proc options group=tk               ; run;
